### ISSUE TITLE
hashTracking and javascript initiated modal

### ISSUE THREAD

**Issue by kategee** [VodkaBears/Remodal#189]
using JavaScript to open the modal, I don't want the hash to appear in the url as upon reload the dynamically populated modal comes up blank. 

using `var options = {hashTracking: false};` with `modal.open();` but url still appears with http://mydomian.com/#modal

Can the hash be omitted from the url?

**Comment by codeclown** [comment]
Just to be clear, you're passing the options to `element.remodal(options)`?

**Comment by kategee** [comment]
Fiddle won't show the issue because you cannot reload it.

Here is a test page: http://test.kaygee.ca/modal.html

Click on the link, it populates the modal text and opens the modal. Reload the page, the modal opens and is blank. The issue: on reload I don't want the modal to launch automatically. I thought by turning `hashTracking: false` the hashtag wouldn't appear in the URL bar, thus the modal would not open on browser refresh.

**Comment by Funfun** [comment]
Having the same issue.

**Comment by codeclown** [comment]
What happens if you move the remodal initialization out of the click-event?

```
var options = {hashTracking: false};
var modal = $( '[data-remodal-id=modal]' ).remodal( options );

$('#go-modal').click(function() {
	$('.remodal p').html('Dynamic text inserted via JavaScript');
	modal.open();
});
```

I think what's happening is that Remodal [sees the hash](https://github.com/VodkaBears/Remodal/blob/master/src/remodal.js#L484), and since the element in question hasn't been explicitly initialized with `hashTracking: false` yet (you do that only after the link is clicked), it will open the modal.

**Comment by kategee** [comment]
You are right, moving it out of the click event works:

http://test.kaygee.ca/modal01.html

Thanks!
