### ISSUE TITLE
Remodal and Backbone

### ISSUE THREAD

**Issue by nlfurniss** [VodkaBears/Remodal#27]
Am I correct in thinking that Remodal doesn't work with Backbone? It seems if modals are inserted into the DOM after Rremodal.js has loaded, they don't trigger.

**Comment by mshwery** [comment]
Actually – he has a great point. You cannot make use of Backbone events because Remodal moves the modal DOM node, destroying any bindings.

**Comment by mshwery** [comment]
@VodkaBears do you have any suggestions on how to handles this since Backbone events are wired up to the current view's node (and its descendants), but Remodal is moving the descendant modal element from its original position in the DOM?

Is it possible to prevent moving the modal element, and instead wrapping it with the `remodal-wrapper` and `remodal-overlay` in its current place?
