### ISSUE TITLE
How to use custom fonts inside remodal window?

### ISSUE THREAD

**Issue by voronkovich** [VodkaBears/Remodal#85]
In the jquery.remodal.css you have rules:
.remodal * {
    font-family: "Exo 2", sans-serif;
}
I think this rules must be deleted, because it override user's custom styles. For example, I can't use Fontawesome as usual <i class="fa fa-code-fork"></i>, I have to add .fa { font-family: Fontawesome ! important; }

**Comment by CollinY2K** [comment]
Agreed. I had to delete most of the css styles because there is entirely too much. In my opinion, the CSS should really be split out between what's needed for modal functionality (like modal positioning) and modal "styles". Any classes that are used to trigger functionality, like close buttons, should have no styles at all. They should only be used as a trigger mechanism. A separate, optional, stylesheet should be used for default styles for those who want it. Otherwise you end up with people trying to override a ton of styles and/or deleting/modifying the provided styles, like I did. Which ultimately is bad if you wish to follow the repo for updates.
